# GitHub Actions 工作流：自动更新 MikroTik CN_IP RSC 文件
# 此工作流支持手动触发和定时调度，执行后会拉取最新 all_cn_cidr.txt，生成 all_cn_cidr.rsc 并提交回仓库

name: Update CN_IP RSC

# 触发条件
on:
  workflow_dispatch:    # 支持在 GitHub UI 或 CLI 中手动触发
  schedule:
    - cron: '0 2 * * *'  # 每天 02:00 UTC 执行

# Workflow 运行所需权限
permissions:
  contents: write      # 允许写入仓库内容，以便推送 .rsc 文件更改

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新 Ubuntu 环境

    # 检出代码，并保持完整历史以便执行 git commit & push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0          # 获取完整 Git 历史
          persist-credentials: true  # 保留 GITHUB_TOKEN 凭据，允许后续推送

      - name: Download CN_IP TXT
        run: |
          # 下载最新的 CN_IP 文本列表
          curl -s https://ispip.clang.cn/all_cn_cidr.txt -o all_cn_cidr.txt

      - name: Generate RSC file
        run: |
          # 生成 .rsc 文件：先清空旧列表，再追加每行添加命令
          echo '/ip firewall address-list remove [find list=CN_IP]' > all_cn_cidr.rsc
          awk '{print "/ip firewall address-list add list=CN_IP address=" $0 " comment=\"China_IP\""}' all_cn_cidr.txt >> all_cn_cidr.rsc

      - name: Commit and push changes
        run: |
          # 配置提交作者信息
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # 添加并提交 .rsc 文件
          git add all_cn_cidr.rsc
          git commit -m "Auto-update CN_IP RSC $(date +'%Y-%m-%d')" || echo "No changes to commit"
          # 推送到远端仓库
          git push origin ${{ github.ref }}
        env:
          # 使用自动提供的 GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
