name: Update CN_IP RSC

on:
  schedule:
    # 每天凌晨 2 点跑一次
    - cron:  '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Download CN_IP TXT
      run: |
        curl -s https://ispip.clang.cn/all_cn_cidr.txt -o all_cn_cidr.txt

    - name: Generate RSC file
      run: |
        echo '/ip firewall address-list remove [find list=CN_IP]' > all_cn_cidr.rsc
        # 每行变成一条添加命令
        awk '{print "/ip firewall address-list add list=CN_IP address="$0" comment=\"China_IP\""}' all_cn_cidr.txt >> all_cn_cidr.rsc

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add all_cn_cidr.rsc
        git commit -m "Auto-update CN_IP RSC $(date +'%Y-%m-%d')" || echo "No changes"
        git push
      env:
        # 使用默认的 GITHUB_TOKEN，无需额外配置
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
